services:
  database:
     image: postgres:latest
     ports:
       - "5432:5432"
     restart: always
     environment:
       POSTGRES_DB: ${DATABASE_NAME}
       POSTGRES_USER: ${DATABASE_USER}
       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
     volumes:
       - postgres_data:/var/lib/postgresql/data
     command:
       - "postgres"
       - "-c"
       - "max_connections=100"
       - "-c"
       - "shared_buffers=256MB"
       - "-c"
       - "effective_cache_size=4GB"
       - "-c"
       - "maintenance_work_mem=256MB"
       - "-c"
       - "log_min_duration_statement=1000"

  gameapi_server:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - database
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      FASTAPI_HOST: ${FASTAPI_HOST}
      FASTAPI_PORT: ${FASTAPI_PORT}

volumes:
  postgres_data:

networks:
  default:
    driver: bridge