class ItemType {
  static const Weapon = 'Weapon';
}


class ItemTier {
  static const Tier1 = 'Tier1';
  static const Tier2 = 'Tier2';
  static const Tier3 = 'Tier3';
  static const Tier4 = 'Tier4';
  static const Tier5 = 'Tier5';
  static const Tier6 = 'Tier6';
}

final Map<String, Map<String, dynamic>> weaponsCatalog = {
    'M1911': {
        'item_name': 'M1911',
        'texture': 'assets/items/placeholder_item.png',
        'category': ItemType.Weapon,
        'tier': ItemTier.Tier1,
        'quick_sell': 150,
        'weight': 1.1,
        'max_durability': 100.0,
        'current_durability': 100.0,
        'caliber': '9x19mm',
        'damage': 7,
        'strength': 0.0,
        'range': 50,
        'accuracy': 60,
        'reload_speed': 2.0,
        'fire_rate': 1.2,
        'magazine_size': 7,
        'armor_penetration': 0,
        'headshot_chance': 15,
        'agility_penalty': -0.5,
        'allowed_attachments': {
            "Muzzle": "Flash Suppressor",
            "Magazine": "Extended Magazine",
            "Laser": "Tactical Laser"
        },
        'attachments': {},
    },
    'Beretta M9': {
        'item_name': 'Beretta M9',
        'texture': 'assets/items/placeholder_item.png',
        'category': ItemType.Weapon,
        'tier': ItemTier.Tier2,
        'quick_sell': 300,
        'weight': 0.95,
        'max_durability': 120.0,
        'current_durability': 120.0,
        'caliber': '9x19mm',
        'damage': 8,
        'strength': 0.0,
        'range': 50,
        'accuracy': 65,
        'reload_speed': 1.7,
        'fire_rate': 1.5,
        'magazine_size': 15,
        'armor_penetration': 5,
        'headshot_chance': 18,
        'agility_penalty': -0.3,
        'allowed_attachments': {
            "Muzzle": "Flash Suppressor",
            "Magazine": "Extended Magazine",
            "Laser": "Tactical Laser"
        },
        'attachments': {},
    },
    'Sawed-off Shotgun': {
        'item_name': 'Sawed-off Shotgun',
        'texture': 'assets/items/placeholder_item.png',
        'category': ItemType.Weapon,
        'tier': ItemTier.Tier1,
        'quick_sell': 200,
        'weight': 2.5,
        'max_durability': 80.0,
        'current_durability': 80.0,
        'caliber': '12 Gauge',
        'damage': 15,
        'strength': 0.0,
        'range': 20,
        'accuracy': 25,
        'reload_speed': 2.5,
        'fire_rate': 0.8,
        'magazine_size': 2,
        'armor_penetration': 10,
        'headshot_chance': 25,
        'agility_penalty': -1.5,
        'allowed_attachments': {
            "Muzzle": "Flash Suppressor"
        },
        'attachments': {},
    },
    'M890': {
        'item_name': 'M890',
        'texture': 'assets/items/placeholder_item.png',
        'category': ItemType.Weapon,
        'tier': ItemTier.Tier2,
        'quick_sell': 400,
        'weight': 3.0,
        'max_durability': 100.0,
        'current_durability': 100.0,
        'caliber': '12 Gauge',
        'damage': 18,
        'strength': 0.0,
        'range': 30,
        'accuracy': 30,
        'reload_speed': 2.3,
        'fire_rate': 1.0,
        'magazine_size': 6,
        'armor_penetration': 12,
        'headshot_chance': 30,
        'agility_penalty': -1.2,
        'allowed_attachments': {
            "Muzzle": "Flash Suppressor"
        },
        'attachments': {},
    },
    'M4A1 Carbine': {
        'item_name': 'M4A1 Carbine',
        'texture': 'assets/items/placeholder_item.png',
        'category': ItemType.Weapon,
        'tier': ItemTier.Tier3,
        'quick_sell': 1500,
        'weight': 3.1,
        'max_durability': 150.0,
        'current_durability': 150.0,
        'caliber': '5.56x45mm NATO',
        'damage': 20,
        'strength': 0.0,
        'range': 300,
        'accuracy': 70,
        'reload_speed': 2.0,
        'fire_rate': 3.0,
        'magazine_size': 30,
        'armor_penetration': 20,
        'headshot_chance': 35,
        'agility_penalty': -2.0,
        'allowed_attachments': {
            "Muzzle": "Flash Suppressor",
            "Magazine": "Extended Magazine",
            "Scope": "Sniper Scope",
            "Stock": "Adjustable Stock",
            "Laser": "Tactical Laser"
        },
        'attachments': {},
    },
    'AAC Honey Badger': {
        'item_name': 'AAC Honey Badger',
        'texture': 'assets/items/placeholder_item.png',
        'category': ItemType.Weapon,
        'tier': ItemTier.Tier5,
        'quick_sell': 3000,
        'weight': 2.8,
        'max_durability': 200.0,
        'current_durability': 200.0,
        'caliber': '300 BLK',
        'damage': 25,
        'strength': 0.0,
        'range': 200,
        'accuracy': 75,
        'reload_speed': 1.5,
        'fire_rate': 3.5,
        'magazine_size': 30,
        'armor_penetration': 25,
        'headshot_chance': 40,
        'agility_penalty': -1.5,
        'allowed_attachments': {
            "Muzzle": "Flash Suppressor",
            "Magazine": "Extended Magazine",
            "Scope": "Sniper Scope",
            "Stock": "Adjustable Stock",
            "Laser": "Tactical Laser"
        },
        'attachments': {},
    },
};
