"""Revision 11

Revision ID: 074e620e9053
Revises: 54b3e275230e
Create Date: 2024-04-16 15:44:21.795146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '074e620e9053'
down_revision: Union[str, None] = '54b3e275230e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing', sa.Column('evasiveness_bonus', sa.Float(), nullable=True))
    op.drop_column('clothing', 'evasiveness')
    op.drop_column('items', 'hash')
    op.add_column('weapon', sa.Column('damage_bonus', sa.Integer(), nullable=False))
    op.drop_column('weapon', 'attachment_one')
    op.drop_column('weapon', 'damage')
    op.drop_column('weapon', 'attachment_two')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon', sa.Column('attachment_two', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('weapon', sa.Column('damage', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('weapon', sa.Column('attachment_one', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('weapon', 'damage_bonus')
    op.add_column('items', sa.Column('hash', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('clothing', sa.Column('evasiveness', mysql.FLOAT(), nullable=True))
    op.drop_column('clothing', 'evasiveness_bonus')
    # ### end Alembic commands ###
