"""Revision 11

Revision ID: 118fd3668066
Revises: ff16e3c2fbf5
Create Date: 2024-04-17 18:12:48.434689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '118fd3668066'
down_revision: Union[str, None] = 'ff16e3c2fbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('equipped_weapon_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('equipped_mask_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('equipped_body_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('equipped_legs_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'equipped_legs_id')
    op.drop_column('inventory', 'equipped_body_id')
    op.drop_column('inventory', 'equipped_mask_id')
    op.drop_column('inventory', 'equipped_weapon_id')
    # ### end Alembic commands ###
