"""Revision

Revision ID: 21875eefa05c
Revises: 3ed0535cd992
Create Date: 2024-04-15 21:18:05.030958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21875eefa05c'
down_revision: Union[str, None] = '3ed0535cd992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('hash', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'hash')
    # ### end Alembic commands ###
