"""Init

Revision ID: 28c621231878
Revises: 
Create Date: 2024-04-11 18:19:55.436226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28c621231878'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'generalmarket', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'user', 'inventory', ['inv_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'generalmarket', type_='foreignkey')
    # ### end Alembic commands ###
