"""Revision 6

Revision ID: 3ed0535cd992
Revises: 69c93e913532
Create Date: 2024-04-15 18:26:55.596469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ed0535cd992'
down_revision: Union[str, None] = '69c93e913532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blackmarket', sa.Column('by_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('blackmarket', 'who_posted')
    op.drop_column('generalmarket', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generalmarket', sa.Column('item_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('blackmarket', sa.Column('who_posted', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('blackmarket', 'by_user')
    # ### end Alembic commands ###
