"""Revision 2

Revision ID: 4a55c6a8be79
Revises: f32ad8f590b2
Create Date: 2024-04-11 12:49:58.104089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a55c6a8be79'
down_revision: Union[str, None] = 'f32ad8f590b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporations', sa.Column('corp_inventory', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('fooditems', sa.Column('health_increase', sa.Integer(), nullable=False))
    op.drop_column('fooditems', 'health_bonus')
    op.add_column('inventory', sa.Column('inventory_items', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'inventory_items')
    op.add_column('fooditems', sa.Column('health_bonus', sa.INTEGER(), nullable=False))
    op.drop_column('fooditems', 'health_increase')
    op.drop_column('corporations', 'corp_inventory')
    # ### end Alembic commands ###
