"""Revision

Revision ID: 4ece146ed92a
Revises: fdf2d0db0ece
Create Date: 2024-04-16 10:59:59.987233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ece146ed92a'
down_revision: Union[str, None] = 'fdf2d0db0ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industrialcraftingrecipes', sa.Column('produced_item_id', sa.Integer(), nullable=False))
    op.drop_constraint('industrialcraftingrecipes_ibfk_1', 'industrialcraftingrecipes', type_='foreignkey')
    op.create_foreign_key(None, 'industrialcraftingrecipes', 'items', ['produced_item_id'], ['id'])
    op.drop_column('industrialcraftingrecipes', 'item_id')
    op.drop_column('industrialcraftingrecipes', 'item_produced')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industrialcraftingrecipes', sa.Column('item_produced', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('industrialcraftingrecipes', sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'industrialcraftingrecipes', type_='foreignkey')
    op.create_foreign_key('industrialcraftingrecipes_ibfk_1', 'industrialcraftingrecipes', 'items', ['item_id'], ['id'])
    op.drop_column('industrialcraftingrecipes', 'produced_item_id')
    # ### end Alembic commands ###
