"""Revision 11

Revision ID: 54b3e275230e
Revises: ef71c1ae7fdd
Create Date: 2024-04-16 13:16:19.799227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54b3e275230e'
down_revision: Union[str, None] = 'ef71c1ae7fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('damage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'damage')
    # ### end Alembic commands ###
