"""Revision 6

Revision ID: 69c93e913532
Revises: 259ad668f618
Create Date: 2024-04-15 18:24:22.020843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69c93e913532'
down_revision: Union[str, None] = '259ad668f618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blackmarket', sa.Column('item_quantity', sa.Integer(), nullable=False))
    op.add_column('generalmarket', sa.Column('sell_price', sa.Integer(), nullable=False))
    op.add_column('generalmarket', sa.Column('item_quantity', sa.Integer(), nullable=False))
    op.drop_column('generalmarket', 'item_sell')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generalmarket', sa.Column('item_sell', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('generalmarket', 'item_quantity')
    op.drop_column('generalmarket', 'sell_price')
    op.drop_column('blackmarket', 'item_quantity')
    # ### end Alembic commands ###
