"""Revision 3

Revision ID: 6f70554d42da
Revises: f8ff8bdfed34
Create Date: 2024-04-15 10:33:09.309347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f70554d42da'
down_revision: Union[str, None] = 'f8ff8bdfed34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
