"""Corporations Reputation & Capital

Revision ID: 998c477a288a
Revises: 2d397f26d9d1
Create Date: 2024-04-09 11:39:02.150100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '998c477a288a'
down_revision: Union[str, None] = '2d397f26d9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporations', sa.Column('capital', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('corporations', sa.Column('reputation', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporations', 'reputation')
    op.drop_column('corporations', 'capital')
    # ### end Alembic commands ###
