"""Removed intelligence & stamina

Revision ID: cab3e42ab7ba
Revises: 998c477a288a
Create Date: 2024-04-09 15:57:13.457062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cab3e42ab7ba'
down_revision: Union[str, None] = '998c477a288a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'intelligence')
    op.drop_column('stats', 'stamina')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('stamina', sa.INTEGER(), nullable=False))
    op.add_column('stats', sa.Column('intelligence', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
