"""Revision

Revision ID: fdf2d0db0ece
Revises: b9c59f2fc6bf
Create Date: 2024-04-16 10:53:29.239909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdf2d0db0ece'
down_revision: Union[str, None] = 'b9c59f2fc6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('equipped_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory', sa.Column('equipped_legs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory', sa.Column('equipped_weapon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory', sa.Column('equipped_mask', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'equipped_mask')
    op.drop_column('inventory', 'equipped_weapon')
    op.drop_column('inventory', 'equipped_legs')
    op.drop_column('inventory', 'equipped_body')
    # ### end Alembic commands ###
