"""Revision 10

Revision ID: ff16e3c2fbf5
Revises: d11199d6b289
Create Date: 2024-04-17 16:38:20.805510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff16e3c2fbf5'
down_revision: Union[str, None] = 'd11199d6b289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
