from .. import (
    ItemType,
    ItemTier
)


weapon_items = {
    'pistol': {
        'M1911': {
            'item_name': 'M1911',
            'category': ItemType.Weapon,
            'tier': ItemTier.Tier1,
            'quick_sell': 150,
            'weight': 1.1,
            'max_durability': 100.0,
            'current_durability': 100.0,
            'caliber': '9x19mm',
            'damage_bonus': 7,
            'strength_bonus': 0.0,
            'range': 50,
            'accuracy': 60,
            'reload_speed': 2.0,
            'fire_rate': 1.2,
            'magazine_size': 7,
            'armor_penetration': 0,
            'headshot_chance': 15,
            'agility_penalty': -0.5,
            'allowed_attachments': '["Muzzle", "Magazine", "Laser"]',
            'attachments': '',
        },
        'beretta_m9': {
            'item_name': 'Beretta M9',
            'category': ItemType.Weapon,
            'tier': ItemTier.Tier2,
            'quick_sell': 300,
            'weight': 0.95,
            'max_durability': 120.0,
            'current_durability': 120.0,
            'caliber': '9x19mm',
            'damage_bonus': 8,
            'range': 50,
            'accuracy': 65,
            'reload_speed': 1.7,
            'fire_rate': 1.5,
            'magazine_size': 15,
            'armor_penetration': 5,
            'headshot_chance': 18,
            'agility_penalty': -0.3,
            'allowed_attachments': '["Muzzle", "Magazine", "Laser"]',
            'attachments': '',
        },
    },
    'shotgun': {
        'sawed_off': {
            'item_name': 'Sawed-off Shotgun',
            'category': ItemType.Weapon,
            'tier': ItemTier.Tier1,
            'quick_sell': 200,
            'weight': 2.5,
            'max_durability': 80.0,
            'current_durability': 80.0,
            'caliber': '12 Gauge',
            'damage_bonus': 15,
            'range': 20,
            'accuracy': 25,
            'reload_speed': 2.5,
            'fire_rate': 0.8,
            'magazine_size': 2,
            'armor_penetration': 10,
            'headshot_chance': 25,
            'agility_penalty': -1.5,
            'allowed_attachments': '["Muzzle"]',
            'attachments': '',
        },
        'm890': {
            'item_name': 'M890',
            'category': ItemType.Weapon,
            'tier': ItemTier.Tier2,
            'quick_sell': 400,
            'weight': 3.0,
            'max_durability': 100.0,
            'current_durability': 100.0,
            'caliber': '12 Gauge',
            'damage_bonus': 18,
            'range': 30,
            'accuracy': 30,
            'reload_speed': 2.3,
            'fire_rate': 1.0,
            'magazine_size': 6,
            'armor_penetration': 12,
            'headshot_chance': 30,
            'agility_penalty': -1.2,
            'allowed_attachments': '["Muzzle"]',
            'attachments': '',
        },
    },
    'assault_rifle': {
        'm4A1_carbine': {
            'item_name': 'M4A1 Carbine',
            'category': ItemType.Weapon,
            'tier': ItemTier.Tier3,
            'quick_sell': 1500,
            'weight': 3.1,
            'max_durability': 150.0,
            'current_durability': 150.0,
            'caliber': '5.56x45mm NATO',
            'damage_bonus': 20,
            'range': 300,
            'accuracy': 70,
            'reload_speed': 2.0,
            'fire_rate': 3.0,
            'magazine_size': 30,
            'armor_penetration': 20,
            'headshot_chance': 35,
            'agility_penalty': -2.0,
            'allowed_attachments': '["Muzzle", "Magazine", "Scope", "Stock", "Laser"]',
            'attachments': '',
        },
        'aac_honey_badger': {
            'item_name': 'AAC Honey Badger',
            'category': ItemType.Weapon,
            'tier': ItemTier.Tier5,
            'quick_sell': 3000,
            'weight': 2.8,
            'max_durability': 200.0,
            'current_durability': 200.0,
            'caliber': '300 BLK',
            'damage_bonus': 25,
            'range': 200,
            'accuracy': 75,
            'reload_speed': 1.5,
            'fire_rate': 3.5,
            'magazine_size': 30,
            'armor_penetration': 25,
            'headshot_chance': 40,
            'agility_penalty': -1.5,
            'allowed_attachments': '["Muzzle", "Magazine", "Scope", "Stock", "Laser"]',
            'attachments': '',
        },
    },
}

